#!/bin/sh
continent="$1"
mixedipv4=$(cat << 'EOF'
Clouvider|London, UK|5200-5209|lon.speedtest.clouvider.net
Airstream|Wisconsin, USA|5201-5205|iperf.airstreamcomm.net
Hybula|Amsterdam, NL|5201-5201|speedtest-nl-oum.hybula.net
Online.net|Paris, FRA|5200-5209|ping.online.net
WebHorizon|Singapore, SG|9201-9205|iperf.sgp.webhorizon.in
EOF
)
mixedipv6=$(cat << 'EOF'
Clouvider|London, UK|5200-5209|lon.speedtest.clouvider.net
Airstream|Wisconsin, USA|5201-5205|iperf.airstreamcomm.net
Hybula|Amsterdam, NL|5201-5201|speedtest-nl-oum.hybula.net
Online.net|Paris, FR|5200-5209|ping6.online.net
WebHorizon|Singapore, SG|9201-9205|iperf.sgp.webhorizon.in
EOF
)
case "$continent" in
  AS)
  ipv4_provider=$(cat << 'EOF'
Uztelecom|Tashkent, UZ|5200-5209|speedtest.uztelecom.uz
WebHorizon|Singapore, SG|9201-9205|iperf.sgp.webhorizon.in
Biznet|Jakarta, ID|5201-5203|iperf.biznetnetworks.com
EOF
  )
  ipv6_provider=$(cat << 'EOF'
Uztelecom|Tashkent, UZ|5200-5209|speedtest.uztelecom.uz
WebHorizon|Singapore, SG|9201-9205|iperf.sgp.webhorizon.in
Biznet|Jakarta, ID|5201-5203|iperf.biznetnetworks.com
EOF
  )
    ;;
  AF)
  ipv4_provider=$mixedipv4
  ipv6_provider=$mixedipv6
    ;;
  NA)
  ipv4_provider=$(cat << 'EOF'
Airstream|Wisconsin, US|5201-5205|iperf.airstreamcomm.net
Clouvider|Dallas, US|5200-5209|dal.speedtest.clouvider.net
OVH|Quebec, CA|5201-5210|bhs.proof.ovh.ca
Hurricane|California, US|5201-5201|iperf.he.net
EOF
  )
  ipv6_provider=$(cat << 'EOF'
Airstream|Wisconsin, US|5201-5205|iperf.airstreamcomm.net
Clouvider|Dallas, US|5200-5209|dal.speedtest.clouvider.net
OVH|Quebec, CA|5201-5210|bhs.proof.ovh.ca
Hurricane|California, US|5201-5201|iperf.he.net
EOF
  )
    ;;
  SA)
  ipv4_provider=$(cat << 'EOF'
Iveloz|Sao Paulo, BR|5201-5209|speedtest.iveloz.net.br
EOF
  )
  ipv6_provider=$(cat << 'EOF'
Iveloz|Sao Paulo, BR|5201-5209|speedtest.iveloz.net.br
EOF
  )
    ;;
  AN)
  ipv4_provider=$mixedipv4
  ipv6_provider=$mixedipv6
    ;;
  EU)
  ipv4_provider=$(cat << 'EOF'
Online.net|Paris, FR|5200-5209|ping.online.net
Clouvider|London, UK|5200-5209|lon.speedtest.clouvider.net
Hybula|Amsterdam, NL|5201-5201|speedtest-nl-oum.hybula.net
Wilhelm.tel|Hamburg, DE|5200-5209|speedtest.wtnet.de
OVH|Roubaix, FR|5201-5210|rbx.proof.ovh.net
EOF
  )
  ipv6_provider=$(cat << 'EOF'
Online.net|Paris, FR|5200-5209|ping.online.net
Clouvider|London, UK|5200-5209|lon.speedtest.clouvider.net
Hybula|Amsterdam, NL|5201-5201|speedtest-nl-oum.hybula.net
WT-NET|Hamburg, DE|5200-5209|speedtest.wtnet.de
OVH|Roubaix, FR|5201-5210|rbx.proof.ovh.net
EOF
  )
    ;;
  OC)
  ipv4_provider=$mixedipv4
  ipv6_provider=$mixedipv6
    ;;
  *)
  ipv4_provider=$mixedipv4
  ipv6_provider=$mixedipv6
    ;;
esac
